RSS_FEEDS = [
'https://www.yahoo.com/news/rss',
'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
'http://feeds.bbci.co.uk/news/video_and_audio/world/rss.xml',
'http://rss.cbc.ca/lineup/canada.xml',
'https://rss-bridge.org/bridge01/?action=display&bridge=ReutersBridge&feed=home%2Ftopnews&format=Atom',
'https://news.ycombinator.com/rss',
'http://feed.torrentfreak.com/Torrentfreak/',
'https://motherboard.vice.com/en_us/rss',
'http://feeds.feedburner.com/Mobilesyrup',
'https://www.producthunt.com/feed?category=undefined',
'http://feeds.wired.com/wired/index',
'http://krebsonsecurity.com/feed/',
'https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml',
'https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml',
'https://noted.lol/rss/',
'https://forums.redflagdeals.com/feed/forum/9',
'https://www.trendhunter.com/rss'
]
